_base_: base.yaml

variants:
  balanced:
    masking.strategy: balanced
  proportional:
    masking.strategy: proportional
  inverse:
    masking.strategy: inverse
  uniform:
    masking.strategy: uniform
